Repository kubesphere/kubeeye, pull requests merged in 2021-02, with the labels that each got.

#42 feature: add a test case on Kind
  .github/workflows/ci.yml
  .github/workflows/kind-test.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#44 Using a much faster go proxy server
  .github/OWNERS
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/settings.yml
  .github/workflows/release-drafter.yml
  Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#52 bugfix: kind test
  .github/workflows/kind-test.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#53 Fix the branch name in the release drafter GitHub Action
  .github/workflows/release-drafter.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#55 [FEATURE] add flag to ke install npd to support custom npd image.
  cmd/add.go
  examples/daemonSet.yaml
  pkg/validator/add.go
Labels: approved, dco-signoff: yes, lgtm, size/M
