Repository kubesphere/kubeeye, pull requests merged in 2022-07, with the labels that each got.

#228 delete modify suggest api
  controllers/kubeeye/update_plugins_results.go
  pkg/suggests/en/modifysuggests.js
  pkg/suggests/zh/modifysuggests.js
Labels: approved, lgtm, size/XL

#230 modify suffix
  pkg/suggests/en/modifysuggests.json
  pkg/suggests/zh/modifysuggests.json
Labels: approved, lgtm, size/XS

#234 fix warning
  README.md
  README_zh.md
  pkg/regorules/rules/FalseNodeConditionsRule.rego
Labels: approved, lgtm, size/S
