Repository kubesphere/kubeeye, pull requests merged in 2022-06, with the labels that each got.

#215 add audit percent
  apis/kubeeye/v1alpha1/clusterinsight_types.go
  config/crd/bases/kubeeye.kubesphere.io_clusterinsights.yaml
  controllers/kubeeye/clusterinsight_controller.go
  deploy/kubeeye.yaml
  pkg/audit/audit.go
  pkg/audit/resources.go
Labels: approved, lgtm, size/XL

#218 update gitignore file
  .gitignore
Labels: approved, lgtm, size/XS

#220 update README.md for resolve the conflicts
  README.md
  README_zh.md
  config/manager/manager.yaml
Labels: approved

#224 update Dockerfile for push image to dockerhub by ci.
  Dockerfile
Labels: approved, lgtm, size/XS

#227 update audit percent and add audit phase
  apis/kubeeye/v1alpha1/clusterinsight_types.go
  config/crd/bases/kubeeye.kubesphere.io_clusterinsights.yaml
  controllers/kubeeye/clusterinsight_controller.go
  controllers/kubeeye/kubeeyecronjob_controller.go
  deploy/kubeeye.yaml
Labels: approved, lgtm, size/M
