Repository kubesphere/kubeeye, pull requests merged in 2022-03, with the labels that each got.

#141 add the audit results level
  .github/workflows/ci.yml
  .github/workflows/kind-test.yaml
  README.md
  README_zh.md
  cmd/ctl/audit.go
  cmd/ctl/install.go
  cmd/ctl/uninstall.go
  go.mod
  pkg/audit/resources.go
  pkg/regorules/rules/CPULimitsRule.rego
  pkg/regorules/rules/CPURequestsRule.rego
  pkg/regorules/rules/allowPrivilegeEscalationRule.rego
  pkg/regorules/rules/canImpersonateUserRoleRule.rego
  pkg/regorules/rules/canModifyResourcesRoleRule.rego
  pkg/regorules/rules/canModifyWorkloadsRoleRule.rego
  pkg/regorules/rules/highRiskCapabilitiesRule.rego
  pkg/regorules/rules/hostIPCRule.rego
  pkg/regorules/rules/hostNetworkRule.rego
  pkg/regorules/rules/hostPIDRule.rego
  pkg/regorules/rules/hostPortRule.rego
  pkg/regorules/rules/imagePullPolicyRule.rego
  pkg/regorules/rules/imageTagMissingRule.rego
  pkg/regorules/rules/imageTagRule.rego
  pkg/regorules/rules/insecureCapabilitiesRule.rego
  pkg/regorules/rules/livenessProbeRule.rego
  pkg/regorules/rules/memoryLimitsRule.rego
  pkg/regorules/rules/memoryRequestsRule.rego
  pkg/regorules/rules/priorityClassRule.rego
  pkg/regorules/rules/privilegedRule.rego
  pkg/regorules/rules/readOnlyRootFilesystemRule.rego
  pkg/regorules/rules/readinessProbeRule.rego
  pkg/regorules/rules/runAsNonRootRule.rego
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README.md
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XXL

#150 Refactor web server
  .github/workflows/kind-test.yaml
  Dockerfile
  Makefile
  cmd/apiserver/app/server.go
  cmd/ctl/apiserver.go
  cmd/ctl/root.go
  cmd/ctl/uninstall.go
  cmd/ke-web/app/server.go
  cmd/ke-web/main.go
  cmd/ke/audit.go
  cmd/ke/install.go
  cmd/ke/main.go
  cmd/ke/root.go
  cmd/ke/uninstall.go
  cmd/main.go
  pkg/kube/getresources.go
  web/.gitignore
  web/.proxyrc
  web/dist/.gitkeep
  web/package.json
  web/src/App.js
  web/src/index.html
  web/src/index.js
  web/src/services/namespace.js
  web/web.go
  web/yarn.lock
Labels: approved, lgtm, size/XXL

#160 Support helm deploy in k8s
  deploy/charts/.helmignore
  deploy/charts/Chart.yaml
  deploy/charts/templates/NOTES.txt
  deploy/charts/templates/_helpers.tpl
  deploy/charts/templates/deployment.yaml
  deploy/charts/templates/kubeeye.yaml
  deploy/charts/templates/leader-election-role.yaml
  deploy/charts/templates/leaderelection-rolebinding.yaml
  deploy/charts/templates/manager-configmap.yaml
  deploy/charts/templates/manager-role.yaml
  deploy/charts/templates/manager-rolebinding.yaml
  deploy/charts/templates/metricsreader-clusterrole.yaml
  deploy/charts/templates/proxy-clusterrole.yaml
  deploy/charts/templates/proxy-rolebinding.yaml
  deploy/charts/templates/service.yaml
  deploy/charts/templates/serviceaccount.yaml
  deploy/charts/templates/tests/test-connection.yaml
  deploy/charts/values.yaml
Labels: approved, lgtm, size/XL

#163 add github action workflows
  .github/workflows/ci.yml
  .github/workflows/e2e-Test.yml
  .github/workflows/kind-test.yaml
  .github/workflows/release.yaml
  .goreleaser.yaml
  Makefile
  hack/docker_build_multiarch.sh
  hack/lib/golang.sh
  hack/lib/init.sh
  hack/lib/logging.sh
  hack/lib/util.sh
  hack/lib/version.sh
Labels: approved, lgtm, size/XXL

#159 support a cluster health score
  apis/kubeeye/v1alpha1/clusterinsight_types.go
  controllers/kubeeye/clusterinsigght_status.go
  controllers/kubeeye/clusterinsight_controller.go
  deploy/kubeeye.yaml
Labels: approved, lgtm, size/L

#164 Fix github action workflows' bugs
  .github/workflows/e2e-Test.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/S

#171 fix bug of deployment error
  config/manager/manager.yaml
  deploy/kubeeye.yaml
Labels: approved, lgtm, size/XS

#181 feat: optimize variable use and some dumplicate code
  pkg/conf/conf.go
  pkg/kube/getresources.go
Labels: lgtm, size/L
