Repository kubesphere/kubeeye, pull requests merged in 2023-09, with the labels that each got.

#304 update release action
  .github/workflows/release.yaml
Labels: approved, lgtm, size/M

#299 Fix log print error
  pkg/plugins/pluginslist.go
  pkg/plugins/result.go
Labels: approved, kind/bug, lgtm, size/XS

#300 chore: slice replace loop
  controllers/kubeeye/clusterinsight_status.go
  pkg/audit/output.go
Labels: approved, lgtm, size/XS
